app:
  name: mayfly-go
  version: 1.2.0
  
server:
  # debug release test
  model: release
  port: 8888
  cors: true
  tls:
    enable: false
    key-file: ./default.key
    cert-file: ./default.pem
  # 静态资源
  static:
    - relative-path: /assets
      root: ./static/assets
  # 静态文件
  static-file:
    - relative-path: /
      filepath: ./static/index.html
    - relative-path: /favicon.ico
      filepath: ./static/favicon.ico
    - relative-path: /config.js
      filepath: ./static/config.js

jwt:
  key: mykey
  # 过期时间单位分钟
  expire-time: 1440

mysql:
  host: localhost:3306
  username: root
  password: 111049
  db-name: mayfly-go
  config: charset=utf8&loc=Local&parseTime=true
  max-idle-conns: 5

log:
   # 日志等级, trace, debug, info, warn, error, fatal
  level: info
  # file:
  #   path: ./
  #   name: mayfly.log